### ISSUE TITLE
替换 validate-commit-msg 为 commitlint

### ISSUE THREAD

**Issue by RunningCoderLee** [uedlinker/cz-conventional-changelog#1]
由于 [validate-commit-msg](https://github.com/conventional-changelog-archived-repos/validate-commit-msg) 已被弃用，所以更换为 [commitlint](https://github.com/marionebl/commitlint)

**Comment by LeeWeisheng** [comment]
参考一下 [@uedlinker/commitlint-config](https://github.com/uedlinker/commitlint-config) 的配置项
